### ISSUE TITLE
Can't change site to some languages

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/frontend-app-account#1052] opened 2024-05-21 21:39 UTC
### Expected behavior

Changing the language for the site should make text appear in other languages.

### Actual behavior

For some languages, it works, but after reloading the page; for others it doesn't, and it goes back to English.

### Steps to reproduce

1. Open up account settings, like https://apps.redwood.demo.edly.io/account/#site-preferences
2. Click or scroll to "Site Preferences".
3. Click "Edit" next to "Site language".
4. Pick a language. I chose French.
5. Click "Save".
6. Reload the page.
7. Notice that the page is still in English and the setting has swapped back to English. (Not sure what happens if your site-wide default is set to something else.)

In a really weird twist, some languages work and some do not!

* Arabic (العربية) - Works! Including right-to-left. Getting it _back_ out of Arabic was a slight challenge, on account of I do not read Arabic.
* Bahasa Indonesia - No luck. The preference sticks, but the site does not change.
* 中文 (简体) (Simplified Chinese) - Works!
* dansk - Works!
* Espaõl (Latinoamérica) - Works!
* Français - No luck.
* German - Works!
* עברית (Hebrew) - Works!
* साइट प्राथमिकताएँ (Hindi) - Works!
* Italian - Molto bene!
* Kiswahili - Poa kichizi kama ndizi. (That means it works.) (Technically it means "Crazy cool like a banana", and it's basically the only Kiswahili I know.)
* 한국어 (대한민국) (Korean, RoK) - No luck. Site does not change, preference does not stick.
* Português - Works!
* Türkçe - Works!
* Українська (Ukranian) - Works!

So a lot of them work, but not all of them. It seems my initial choice of French was sort of lucky here - I might not have realized this was broken otherwise.

Original issue: https://github.com/openedx/wg-build-test-release/issues/347

**Comment by brian-smith-tcril** [comment] 2024-05-22 14:07
Looking at the account MFE specifically (https://github.com/openedx/openedx-translations/blob/main/translations/frontend-app-account/src/i18n/messages/)

> Bahasa Indonesia - No luck. The preference sticks, but the site does not change.

I assume this is coming from https://github.com/openedx/openedx-translations/blob/main/translations/frontend-app-account/src/i18n/messages/id.json, which appears to have English strings in it

> Français - No luck.

It seems we only have `fr_CA` in the account MFE https://github.com/openedx/openedx-translations/blob/main/translations/frontend-app-account/src/i18n/messages/fr_CA.json

> 한국어 (대한민국) (Korean, RoK) - No luck. Site does not change, preference does not stick.

There is no `ko` file in there

**Comment by mariajgrimaldi** [comment] 2024-05-24 20:25
Thank you, @brian-smith-tcril; I understand better now. Do you know what the process is for supporting those languages? At least for the ones listed in the account MFE.

**Comment by mariajgrimaldi** [comment] 2024-06-02 15:43
Also, @brian-smith-tcril: there's a cors error when changing the language from the account page. You can see it in detail here: https://github.com/openedx/wg-build-test-release/issues/347#issuecomment-2137186119

We have a similar cors error in the account MFE when trying to disconnect a TPA account association: https://github.com/openedx/wg-build-test-release/issues/376#issue-2328128813

Is this likely related to why the language changes are not reflected immediately but after reloading? When changing the language, the CORS error in the account page also happens in Quince, so the changes are not seen immediately either.

**Comment by mariajgrimaldi** [comment] 2024-06-03 19:53
So... I tested this in the quince sandbox, and it failed:

[Screencast from 03-06-24 15:19:59.webm](https://github.com/openedx/frontend-app-account/assets/64440265/8a402850-1a70-44d3-a558-1fe8618d48b4)

And then tested it in one of our internal installations (tutor k8s + other custom configurations for Kubernetes), and it worked. Even for français. Then I went through the k8s manifests configs and found this:`

ALLOWED_HOSTS = ["*"]`

After removing it, I was able to reproduce the error.

**Comment by mariajgrimaldi** [comment] 2024-06-06 02:25
So I was testing in our quince installation and realized that this only fails when the LMS_HOST differs from MFE_HOST. If they are the same, I can change the languages and the account MFE behaves correctly, because there is no course issue (same domain).

@cmltaWt0: is that what happens in your installation where you can change the languages?

**Comment by cmltaWt0** [comment] 2024-06-06 07:52
@mariajgrimaldi Yeap. 
LMS: https://axim-mfe.raccoongang.net/
MFE: https://apps.axim-mfe.raccoongang.net/

**Comment by mariajgrimaldi** [comment] 2024-06-10 15:58
@arbrandes @brian-smith-tcril: What do you think about the CORS issue findings? I believe at least some of it might be related to the language not changing immediately but after reloading.

**Comment by brian-smith-tcril** [comment] 2024-06-10 16:32
I haven't done any intensive investigation into the CORS issue but I would assume that it is something that needs to be addressed on the Tutor side.

**Comment by regisb** [comment] 2024-09-16 13:04
When I click "save" the following happens:

1. POST to <LMS>/i18n/setlang/
2. redirect to GET <LMS>/ (no idea why)
3. redirect to GET <LMS>/dashboard (probably because the dashboard is the landing page)
4. redirect to GET <MFE>/learner-dashboard (probably because the LMS is configured to point to the MFE dashboard)
5. for some unknown reason this is considered attempt to make a CORS request to GET <MFE>

**Comment by regisb** [comment] 2024-09-16 13:08
I commented on the [Tutor issue](https://github.com/overhangio/tutor-mfe/issues/223). As far as I understand, this has nothing to do with Tutor.

A side question is: why was this issue no longer considered a release blocker? (on June 4th)

**Comment by mariajgrimaldi** [comment] 2024-09-23 12:59
Thank you, @regisb, for sharing your findings. I was looking into step 2, and it turns out Django is responsible for the redirection: https://github.com/django/django/blob/4.2.16/django/views/i18n.py#L45-L62 https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#django.views.i18n.set_language

Could this be fixed by sending a `next=` parameter when calling `setlang` [here](https://github.com/openedx/frontend-app-account/blob/116c30663b6df65bc39058541f5786c292f874a1/src/account-settings/site-language/service.js#L25-L31) so it redirects to the same page?

**Comment by regisb** [comment] 2024-09-23 13:45
Great catch Maria! That's what I call some deep digging :) I disagree with your conclusion, though. If I understand correctly, we go through `next_url = "/"` (line 44) because we have `request.accepts("text/html")` (line 32). See the request headers:

![changelang](https://github.com/user-attachments/assets/1c419f3f-f870-4f32-ad17-593761ee7fea)

Our "happy path" would be to get a 204 response (line 45). And for that we should remove the "text/html, */*" values from the `Accept` header. I managed to reproduce this with the "edit and resend" feature in Firefox developer console. When we remove these values from the header, we are successfully getting a 204 response.

This is how we should Thus, we should override the "Accept" header

**Comment by mariajgrimaldi** [comment] 2024-09-23 15:29
Thanks, @regisb. I completely missed that :)

**Comment by mariajgrimaldi** [comment] 2024-10-07 11:18
@arbrandes, I believe what Regis described above is also happening when trying to unlink SSO accounts:

![image](https://github.com/user-attachments/assets/55c46812-8151-4fc1-9d82-d5a482a6ac49)

Which also raises a misleading CORS issue.

**Comment by mariajgrimaldi** [comment] 2024-10-16 21:11
Here's the PR that might solve this: https://github.com/openedx/frontend-app-account/pull/1139

@arbrandes could you help us take a look? Thanks!

**Comment by arbrandes** [comment] 2024-10-22 15:41
It seems #1139 fixed this.  Closing!

**Closed by arbrandes** 2024-10-22 15:41 UTC
Labels: bug, release testing, release blocker

**Comment by deborahgu** [comment] 2024-11-07 17:04
Thanks for doing all this! FWIW, if you switch to one of the 4 languages @BryanttV identified as still not working because of missing translation files in the PR

* ca
* fr
* ko-kr
* pl

the cookie is still set, which has weird effects because there is a small number of translated strings that get picked up. (I noticed this when, without having ever seen this GH issue, i saw the same bug, and I must have left my setting on "French", and then my English page was being set `lang=fr` and  firefox  was offering to translate the pages.  (I didn't figure it out until I went to a django admin page which _did_ translate.)

Is there a ticket to either  remove the 4 broken languages from the drop down or add the translation files? I didn't see one linked here . No matter what, the current experience is still buggy.
